apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: beeai-oidc-providers
  labels:
    app.kubernetes.io/component: beeai-ui
    app: beeai-ui
  namespace: default
stringData:
  providers.json: |
    {{- toJson .Values.oidc.providers | nindent 4 -}}
